apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-logger-deployment
spec:
  selector:
    matchLabels:
      app: package-logger
  replicas: 1
  template:
    metadata:
      labels:
        app: package-logger
    spec:
      containers:
      - name: package-logger
        image: johnmandrus/package-logger:latest
        ports: