apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-detector-deployment
spec:
  selector:
    matchLabels:
      app: detector
  replicas: 1
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: detector
        image: johnmandrus/package-detector:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0   
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0