apiVersion: apps/v1
kind: Deployment
metadata:
  name: package-detector-deployment
spec:
  selector:
    matchLabels:
      app: package-detector
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: package-detector
    spec:
      containers:
      - name: package-detector
        image: jkumariucb/package-detector:v1
        env:
        - name: DISPLAY
          value: ":0"
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-cam
        volumeMounts:
        - mountPath: /tmp/.X11-unix
          name: video
        securityContext:
          privileged: true
      volumes:
      - name: dev-cam
        hostPath:
          path: /dev/video0
      volumes:
      - name: video
        hostPath:
          path: /tmp/.X11-unix
